### PR TITLE
Jmx object filters

### PR DESCRIPTION
**Pull request by neophenix**
allow users to set mbean_properties_(.+) that will act like an OR filter for mbean objects, if they match the props, let them through.

This means we don't have to pull every object and pass it back to noit, potentially killing it while it tries to parse the large XML docs that can be created.

### CODE REVIEW

**Comment by postwait** [comment]
Do we need an update to the jmx xml to state that these propoerties are allowed? (docs update)

**Comment by neophenix** [comment]
Yeah, where are the docs for these located and I'll do that

**Comment by postwait** [comment]
Shit. Doesn't look like we have docs for this.   But adding a jmx.xml in the modules/ directory would allow for docs.  If you make it look like any of the other xml files, we can autogen docs off it.

**Comment by neophenix** [comment]
OK, I think that is what you meant

**Pull request merged**
