### PR TITLE
Fix detection of libmtev in configure.in

### PR DESCRIPTION
**Pull request by flyerman**

### CODE REVIEW

**Comment by postwait** [comment]
Shouldn't libmtev depend on -lck and -ljlog already?  An app should be able to -lmtev and have it automatically pull in all dependent libs (include ck and jlog).

On what platform is this error happening?

**Comment by flyerman** [comment]
It does indeed. The issue is when installing libck and libjlob in custom locations.
This happening on CentOS.

**Comment by postwait** [comment]
Did you build libmtev with -Wl,-rpath -Wl,/custom/lib/location ?

It sounds like libmtev was build without a correct runpath

**Comment by flyerman** [comment]
I have not used rpath. I'll take a look thanks.

**Pull request closed without merging**
