### PR TITLE
Websockets and externalization of histogram code into libcircllhist

### PR DESCRIPTION
**Pull request by rileyberton**
This requires `--enable-wslay` support in libmtev. And it requires a package for `libcircllhist` (https://github.com/circonus-labs/libcircllhist).

This allows you to connect a websocket to `http(s)://<broker>/livestream` and send down a request for data like:

```
                          var check = {
                              "period_ms": 500,
                              "check_uuid": "f7cea020-f19d-11dd-85a6-cb6d3a2207dc",
                              "metrics" : ["check_cnt", "checks_run"]
                          };
                          var string = JSON.stringify(check);
                          connection.sendUTF(string);
```

And you will get back individual livestreamed metrics at `period_ms` which are filtered to the names in `metrics`.  You can get all metrics under that check by omitting the `metrics` field from the request.

### CODE REVIEW

**Comment by postwait** [comment]
This looks good to me.

**Comment by esproul** [comment]
Tested a build from this branch and found that a couple additional binaries are linking libcircllhist, in addition to the expected histogram.so module:

* noitd: not surprising, hist_* functions used in noit_metric.c.
* postgres.so: Cannot see why this one is linking libcircllhist as it references none of its functions. Appears to be a direct linkage, i.e., not an indirect dependency.

Neither of these are show-stoppers; they are simply unexpected (at least by me). The postgres module is the more perplexing.

**Comment by esproul** [comment]
I get this error building on EL6:

```
- compiling noit_metric.c
In file included from noit_metric.c:1:
noit_metric.h:82: error: expected specifier-qualifier-list before 'uint64_t'
noit_metric.c: In function 'noit_metric_to_json':
noit_metric.c:23: error: 'noit_metric_value_t' has no member named 'whence_ms'
noit_metric.c:31: error: 'noit_metric_value_t' has no member named 'type'
noit_metric.c:31: error: 'noit_metric_value_t' has no member named 'type'
noit_metric.c:35: error: 'noit_metric_value_t' has no member named 'type'
noit_metric.c:43: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:45: error: 'noit_metric_value_t' has no member named 'type'
noit_metric.c:53: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:59: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:65: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:71: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:76: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:102: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:102: error: 'noit_metric_value_t' has no member named 'value'
noit_metric.c:109: error: 'uint64_t' undeclared (first use in this function)
noit_metric.c:109: error: (Each undeclared identifier is reported only once
noit_metric.c:109: error: for each function it appears in.)
noit_metric.c:109: error: expected ';' before 'bc'
noit_metric.c:110: error: 'bc' undeclared (first use in this function)
make[1]: *** [noit_metric.o] Error 1
```

**Comment by esproul** [comment]
Builds correctly on Circonus-supported platforms. LGTM.

**Pull request merged**
